Host wolgye2
    HostName 100.114.186.95
    User wolgye2
Host mapo2
    HostName 100.67.119.36
    User mapo2
Host mia2
    HostName 100.77.33.70
    User mia2
Host mooner2
    HostName 100.87.102.90
    User mooner2
Host wangsim2
    HostName 100.71.28.69
    User wangsim2
Host *
    IdentityFile /home/sdg/.ssh/id_ed25519
    IdentitiesOnly yes
    BatchMode yes
    StrictHostKeyChecking yes
    ConnectTimeout 8
    ServerAliveInterval 30
    ServerAliveCountMax 3
