instances:
- id: prod_mk_027
  class: Product
  data:
    name: 낙지볶음
- id: prod_sp_009
  class: Product
  data:
    name: 손질 갑오징어
- id: prod_mk_021
  class: Product
  data:
    name: 문어전복해물탕
- id: prod_sp_005
  class: Product
  data:
    name: 활전복
- id: prod_mk_017
  class: Product
  data:
    name: 얼큰한 꽃게탕
- id: prod_mk_023
  class: Product
  data:
    name: 동태알탕
- id: prod_sp_026
  class: Product
  data:
    name: 알곤이세트
- id: prod_mk_004
  class: Product
  data:
    name: 코다리알탕
- id: prod_sp_017
  class: Product
  data:
    name: 주꾸미
- id: prod_gj_004
  class: Product
  data:
    name: 간장새우장
- id: prod_mk_008
  class: Product
  data:
    name: 국산문어 해물탕
- id: prod_mk_005
  class: Product
  data:
    name: 시원한 새우탕
- id: prod_sp_019
  class: Product
  data:
    name: 흰다리새우
- id: prod_mk_009
  class: Product
  data:
    name: 순살 아귀찜
- id: prod_sp_020
  class: Product
  data:
    name: 흰다리새우살(꼬리있음)
- id: prod_sp_006
  class: Product
  data:
    name: 국산홍가리비살
- id: prod_sp_001
  class: Product
  data:
    name: 가리비관자
- id: prod_mk_014
  class: Product
  data:
    name: 낙지전복해물탕
- id: prod_sp_018
  class: Product
  data:
    name: 절단낙지
- id: prod_mk_025
  class: Product
  data:
    name: 낙곱새
- id: prod_mk_010
  class: Product
  data:
    name: 프리미엄 낙곱새
- id: prod_sp_023
  class: Product
  data:
    name: 주꾸미
- id: prod_mk_018
  class: Product
  data:
    name: 낙곱새
- id: prod_mk_026
  class: Product
  data:
    name: 주꾸미볶음
- id: prod_mk_003
  class: Product
  data:
    name: 알탕
- id: prod_mk_006
  class: Product
  data:
    name: 골뱅이탕
- id: prod_sp_002
  class: Product
  data:
    name: 흰다리새우
- id: prod_mk_019
  class: Product
  data:
    name: 주꾸미볶음
- id: prod_sp_011
  class: Product
  data:
    name: 손질 주꾸미
- id: prod_mk_029
  class: Product
  data:
    name: 순살아귀찜
- id: prod_mk_007
  class: Product
  data:
    name: 대구탕
- id: prod_sp_007
  class: Product
  data:
    name: 국산흑골뱅이
- id: prod_gj_001
  class: Product
  data:
    name: 국산 알베기 간장게장
- id: prod_sp_027
  class: Product
  data:
    name: 문어소라슬라이스
- id: prod_mk_011
  class: Product
  data:
    name: 주꾸미볶음
- id: prod_mk_016
  class: Product
  data:
    name: 볼락 매운탕
- id: prod_sp_021
  class: Product
  data:
    name: 흰다리새우살
- id: prod_gj_002
  class: Product
  data:
    name: 간장게장
- id: prod_mk_020
  class: Product
  data:
    name: 낙지볶음
- id: prod_mk_015
  class: Product
  data:
    name: 동태알탕
- id: prod_sp_003
  class: Product
  data:
    name: 손질 흰다리새우살(대)
- id: prod_sp_015
  class: Product
  data:
    name: 가리비관자
- id: prod_mk_030
  class: Product
  data:
    name: 대구매운탕
- id: prod_mk_022
  class: Product
  data:
    name: 낙지전복해물탕
- id: prod_mk_001
  class: Product
  data:
    name: 문어전복해물탕
- id: prod_mk_013
  class: Product
  data:
    name: 문어전복해물탕
- id: prod_sp_010
  class: Product
  data:
    name: 손질 낙지
- id: prod_sp_022
  class: Product
  data:
    name: 가리비관자
- id: prod_sp_016
  class: Product
  data:
    name: 알곤이세트
- id: prod_mk_012
  class: Product
  data:
    name: 낙지볶음
- id: prod_mk_002
  class: Product
  data:
    name: 낙지전복해물탕
- id: prod_sp_004
  class: Product
  data:
    name: 손질 흰다리새우살
- id: prod_sp_012
  class: Product
  data:
    name: 흰다리새우
- id: prod_sp_025
  class: Product
  data:
    name: 절단낙지
- id: prod_sp_024
  class: Product
  data:
    name: 손질낙지
- id: prod_mk_028
  class: Product
  data:
    name: 갑오징어볶음
- id: prod_sp_008
  class: Product
  data:
    name: 백생합
- id: prod_gj_003
  class: Product
  data:
    name: 간장 새우장
- id: prod_sp_013
  class: Product
  data:
    name: 흰다리새우살(대)
- id: prod_sp_014
  class: Product
  data:
    name: 흰다리새우살
- id: prod_mk_024
  class: Product
  data:
    name: 푸짐한 알탕
