instances:
- id: prod_mp_nakji_bokkeum
  class: Product
  data:
    name: 낙지볶음
- id: prod_ws_gabo
  class: Product
  data:
    name: 손질 갑오징어
- id: prod_mp_muneotang
  class: Product
  data:
    name: 문어전복해물탕
- id: prod_ws_jeonbok
  class: Product
  data:
    name: 활전복
- id: prod_wg_kkotgetang
  class: Product
  data:
    name: 얼큰한 꽃게탕
- id: prod_mp_dongtae
  class: Product
  data:
    name: 동태알탕
- id: prod_mp_algoni
  class: Product
  data:
    name: 알곤이세트
- id: prod_ws_kodari
  class: Product
  data:
    name: 코다리알탕
- id: prod_wg_jukkumi
  class: Product
  data:
    name: 주꾸미
- id: prod_mp_saeujang
  class: Product
  data:
    name: 간장새우장
- id: prod_ws_muneotang_kr
  class: Product
  data:
    name: 국산문어 해물탕
- id: prod_mp_saeu
  class: Product
  data:
    name: 흰다리새우
- id: prod_ws_agwijjim
  class: Product
  data:
    name: 순살 아귀찜
- id: prod_mp_saeusal_kkori
  class: Product
  data:
    name: 흰다리새우살(꼬리있음)
- id: prod_ws_honggaribi
  class: Product
  data:
    name: 국산홍가리비살
- id: prod_ws_gwanja
  class: Product
  data:
    name: 가리비관자
- id: prod_wg_nakjitang
  class: Product
  data:
    name: 낙지전복해물탕
- id: prod_wg_nakji_jeoldan
  class: Product
  data:
    name: 절단낙지
- id: prod_mp_nakgopsae
  class: Product
  data:
    name: 낙곱새
- id: prod_ws_nakgopsae_p
  class: Product
  data:
    name: 프리미엄 낙곱새
- id: prod_mp_jukkumi
  class: Product
  data:
    name: 주꾸미
- id: prod_wg_nakgopsae
  class: Product
  data:
    name: 낙곱새
- id: prod_mp_jukkumi_bokkeum
  class: Product
  data:
    name: 주꾸미볶음
- id: prod_ws_altang
  class: Product
  data:
    name: 알탕
- id: prod_ws_saeu
  class: Product
  data:
    name: 흰다리새우
- id: prod_wg_jukkumi_bokkeum
  class: Product
  data:
    name: 주꾸미볶음
- id: prod_ws_jukkumi_son
  class: Product
  data:
    name: 손질 주꾸미
- id: prod_mp_agwijjim
  class: Product
  data:
    name: 순살아귀찜
- id: prod_ws_daegutang
  class: Product
  data:
    name: 대구탕
- id: prod_ws_golbaengi
  class: Product
  data:
    name: 국산흑골뱅이
- id: prod_ws_albegi
  class: Product
  data:
    name: 국산 알베기 간장게장
- id: prod_wg_muneosora
  class: Product
  data:
    name: 문어소라슬라이스
- id: prod_ws_jukkumi_bokkeum
  class: Product
  data:
    name: 주꾸미볶음
- id: prod_wg_bollak
  class: Product
  data:
    name: 볼락 매운탕
- id: prod_mp_saeusal
  class: Product
  data:
    name: 흰다리새우살
- id: prod_ws_gejang
  class: Product
  data:
    name: 간장게장
- id: prod_wg_nakji_bokkeum
  class: Product
  data:
    name: 낙지볶음
- id: prod_wg_dongtae
  class: Product
  data:
    name: 동태알탕
- id: prod_ws_saeusal_son_L
  class: Product
  data:
    name: 손질 흰다리새우살(대)
- id: prod_wg_gwanja
  class: Product
  data:
    name: 가리비관자
- id: prod_wg_daegu_maeun
  class: Product
  data:
    name: 대구매운탕
- id: prod_mp_nakjitang
  class: Product
  data:
    name: 낙지전복해물탕
- id: prod_ws_muneotang
  class: Product
  data:
    name: 문어전복해물탕
- id: prod_wg_muneotang
  class: Product
  data:
    name: 문어전복해물탕
- id: prod_ws_nakji
  class: Product
  data:
    name: 손질 낙지
- id: prod_mp_gwanja
  class: Product
  data:
    name: 가리비관자
- id: prod_wg_algoni
  class: Product
  data:
    name: 알곤이세트
- id: prod_ws_nakji_bokkeum
  class: Product
  data:
    name: 낙지볶음
- id: prod_ws_nakjitang
  class: Product
  data:
    name: 낙지전복해물탕
- id: prod_ws_saeusal_son
  class: Product
  data:
    name: 손질 흰다리새우살
- id: prod_wg_saeu
  class: Product
  data:
    name: 흰다리새우
- id: prod_mp_nakji_jeoldan
  class: Product
  data:
    name: 절단낙지
- id: prod_mp_nakji
  class: Product
  data:
    name: 손질낙지
- id: prod_mp_gabo_bokkeum
  class: Product
  data:
    name: 갑오징어볶음
- id: prod_ws_saenghap
  class: Product
  data:
    name: 백생합
- id: prod_ws_saeujang
  class: Product
  data:
    name: 간장 새우장
- id: prod_wg_saeusal_L
  class: Product
  data:
    name: 흰다리새우살(대)
- id: prod_wg_saeusal
  class: Product
  data:
    name: 흰다리새우살
- id: prod_mp_altang_pujim
  class: Product
  data:
    name: 푸짐한 알탕
